// ISO/IEC 27001:2022 Annex A — 93 Kontrol
// Her kontrol için: kod, ad, amaç, denetçi soruları, kanıt, tipik bulgu, tipik öneri
const ANNEX_A = [
  // ============ A.5 ORGANİZASYONEL (37) ============
  {code:"A.5.1", name:"Bilgi güvenliği politikaları", themeLabel:"A.5 ORG",
    purpose:"Üst yönetim tarafından onaylı, yayımlanmış ve gözden geçirilen politika seti olması.",
    questions:["Ana politika ne zaman onaylandı ve en son ne zaman gözden geçirildi?","Alt politikalar (erişim, şifreleme, BC vb.) ana politikaya nasıl bağlı?"],
    evidence:["İmzalı politika","Gözden geçirme kayıtları","Yayın/duyuru kanıtı"],
    bulgu:"Politika 2 yıldır gözden geçirilmemiş, mevcut organizasyona uymuyor.",
    oneri:"Yıllık revizyon takvimi kurun; değişiklik tetikleyici olaylar (M&A, yeni servis) için ad-hoc review süreci tanımlayın."},
  {code:"A.5.2", name:"Bilgi güvenliği rolleri ve sorumlulukları", themeLabel:"A.5 ORG",
    purpose:"Rollerin net tanımı, atama ve iletişimi.",
    questions:["BGYS sorumlusu kim, nereye raporluyor?","Rol tanımları iş tanımlarında (JD) yer alıyor mu?"],
    evidence:["Organizasyon şeması","İş tanımları","RACI matrisi"],
    bulgu:"BGYS sorumlusu yok ya da yalnızca IT içinden atanmış, üst yönetime erişimi kısıtlı.",
    oneri:"CISO/BGYS sorumlusunu icra komitesine raporlayan bağımsız rolde konumlandırın."},
  {code:"A.5.3", name:"Görevlerin ayrılığı", themeLabel:"A.5 ORG",
    purpose:"Çelişen görevlerin aynı kişide toplanmaması (SoD).",
    questions:["Geliştirme–operasyon–onay zincirini aynı kişi kapatabiliyor mu?","Finansal sistemlerde SoD matrisi var mı?"],
    evidence:["SoD matrisi","Rol-yetki eşleşme raporu","İstisna kayıtları"],
    bulgu:"Bir geliştirici prod'a kendi yazdığı kodu onaysız deploy edebiliyor.",
    oneri:"4-gözlü onay kuralı + CI/CD'de zorunlu reviewer; istisnalar için compensating kontrol kurgulayın."},
  {code:"A.5.4", name:"Yönetim sorumluluğu", themeLabel:"A.5 ORG",
    purpose:"Yönetimin BGYS'ye taahhüdü, liderlik ve yönlendirme.",
    questions:["Üst yönetim YGG'ye düzenli katılıyor mu?","Güvenlik bütçesi nasıl onaylandı?"],
    evidence:["YGG tutanakları","Bütçe onay kayıtları","Üst yönetim iletişimi"],
    bulgu:"Yönetim BGYS'ye yıl içinde bir kez (sertifikasyon öncesi) angaje oluyor.",
    oneri:"Çeyreklik CISO sunumu + KPI dashboard'u yönetim toplantısına daimi gündem olarak ekleyin."},
  {code:"A.5.5", name:"Yetkililerle iletişim", themeLabel:"A.5 ORG",
    purpose:"Düzenleyici, CERT ve kolluk ile iletişim kanalı.",
    questions:["KVKK/Veri Koruma Kurulu ve ulusal CERT için tanımlı kontak var mı?","Bildirim sürelerini kim takip ediyor?"],
    evidence:["İletişim listesi","Bildirim prosedürü","Son ihlal bildirim örneği"],
    bulgu:"Veri ihlali bildirimi için 72 saatlik süre sahibi tanımsız.",
    oneri:"DPO + Hukuk + CISO üçlü RACI'si; incident response playbook'una hazır bildirim taslakları ekleyin."},
  {code:"A.5.6", name:"Özel ilgi gruplarıyla iletişim", themeLabel:"A.5 ORG",
    purpose:"Endüstri ISAC, forum ve güvenlik topluluklarıyla bağlantı.",
    questions:["Tehdit istihbaratı hangi kaynaklardan geliyor?","Üyelikler güncel mi?"],
    evidence:["ISAC/forum üyelik","Tehdit bülten arşivi","Paylaşım kayıtları"],
    bulgu:"Tehdit istihbaratı yalnızca ücretsiz bülten taramasıyla sınırlı.",
    oneri:"En az 1 sektörel ISAC + 1 ticari TI beslemesi + iç triage süreci tanımlayın."},
  {code:"A.5.7", name:"Tehdit istihbaratı", themeLabel:"A.5 ORG",
    purpose:"Tehdit bilgisinin toplanması, analiz ve aksiyona dönüştürülmesi.",
    questions:["TI bulguları SIEM/detection kurallarına nasıl iniyor?","Son 3 ayda TI'den üretilen aksiyon kaç tane?"],
    evidence:["TI platform/raporlar","Kurallara yansıma kaydı","Triage tutanakları"],
    bulgu:"TI raporları toplanıyor ama hiçbiri detection kuralına dönüşmemiş.",
    oneri:"TI → Detection pipeline'ı kurun; her IOC için SIEM kural üretimi + kapanış kaydı zorunlu olsun."},
  {code:"A.5.8", name:"Proje yönetiminde bilgi güvenliği", themeLabel:"A.5 ORG",
    purpose:"Projelerin başından sonuna güvenlik gereksinimi entegre edilmesi.",
    questions:["Yeni proje kickoff'unda güvenlik checklist'i var mı?","Hangi projelerde tehdit modelleme yapıldı?"],
    evidence:["Proje şablonu","Tehdit modelleme dokümanları","Go-live gate checklist"],
    bulgu:"Proje güvenliği yalnızca go-live öncesi pentest ile değerlendiriliyor.",
    oneri:"Discovery → Design → Build → Launch gate'lerinin her birine güvenlik review'ü koyun."},
  {code:"A.5.9", name:"Bilgi ve varlıkların envanteri", themeLabel:"A.5 ORG",
    purpose:"Varlık envanterinin güncel ve sahipli olması.",
    questions:["Envanter ne sıklıkla güncellenir?","Shadow IT nasıl tespit ediliyor?"],
    evidence:["Varlık envanteri","Otomatik discovery raporu","Sahiplik atamaları"],
    bulgu:"Cloud varlıkları manuel tutuluyor, 3 aylık tagging kaydı yok.",
    oneri:"CMDB + CSPM otomasyonu; tag compliance raporunu haftalık incelemeye alın."},
  {code:"A.5.10", name:"Bilgi ve varlıkların kabul edilebilir kullanımı", themeLabel:"A.5 ORG",
    purpose:"Kurum varlıklarının kullanım kurallarının dokümante ve kabul edilmiş olması.",
    questions:["AUP çalışan onboarding'de imzalanıyor mu?","Kişisel cihaz (BYOD) kullanımı nasıl yönetiliyor?"],
    evidence:["İmzalı AUP","BYOD politikası","İhlal kaydı örneği"],
    bulgu:"AUP imzası yalnızca elektronik onay kutucuğu, içerik değişiminde yeniden kabul istenmemiş.",
    oneri:"Yıllık reacknowledgement + politika değişikliklerinde diff tabanlı onay akışı kurun."},
  {code:"A.5.11", name:"Varlıkların iadesi", themeLabel:"A.5 ORG",
    purpose:"İşten çıkışta cihaz/bilgi iadesinin eksiksiz yapılması.",
    questions:["Exit checklist var mı ve kim imzalıyor?","Uzak çalışanlardan iade nasıl sağlanıyor?"],
    evidence:["Exit formu","Envanter kapanış kaydı","Kargo/teslim tutanağı"],
    bulgu:"Son 3 ayda ayrılan çalışanların 2'sinde hâlâ aktif VPN hesabı mevcut.",
    oneri:"IK → IT exit ticket otomasyonu; son gün T+0 hesap devre dışı; donanım iade SLA 5 iş günü."},
  {code:"A.5.12", name:"Bilgilerin sınıflandırılması", themeLabel:"A.5 ORG",
    purpose:"Bilginin hassasiyetine göre sınıflandırılması.",
    questions:["Sınıflandırma şeması kaç seviyeli?","Örnek bir belgenin sınıflandırma etiketi nerede?"],
    evidence:["Sınıflandırma politikası","Örnek etiketli belge","DLP kural setleri"],
    bulgu:"Sınıflandırma politikası mevcut ama belgelerin %70'i etiketsiz.",
    oneri:"Office/e-posta sensitivity labels + AIP/Purview; yeni oluşturulan belgelere zorunlu label."},
  {code:"A.5.13", name:"Bilgilerin etiketlenmesi", themeLabel:"A.5 ORG",
    purpose:"Sınıflandırmanın tutarlı etiketler ile görünür kılınması.",
    questions:["E-posta ve dosyalarda etiketler hangi araçla uygulanıyor?","Fiziksel belgelerde etiket zorunlu mu?"],
    evidence:["Etiket şablonu","Örnek çıktılar","Denetim log'u"],
    bulgu:"Sensitivity label uygulanıyor ama downgrade (Gizli → Genel) için justification istenmiyor.",
    oneri:"Downgrade onay akışı + log'unu aktive edin; quarterly sample review yapın."},
  {code:"A.5.14", name:"Bilgi aktarımı", themeLabel:"A.5 ORG",
    purpose:"Dahili/harici veri paylaşımının güvenli kanallarla yapılması.",
    questions:["Harici paylaşım için hangi kanallar onaylı?","Şifreleme politikası nedir?"],
    evidence:["Transfer politikası","SFTP/secure link logları","NDA kayıtları"],
    bulgu:"Finans ekibi raporları hâlâ parolasız e-posta ekiyle paylaşıyor.",
    oneri:"DLP kuralı + onaylı paylaşım portalı; e-posta ekleri otomatik şifrelensin."},
  {code:"A.5.15", name:"Erişim kontrolü", themeLabel:"A.5 ORG",
    purpose:"Varlıklara erişimin tanımlı kural seti üzerinden verilmesi.",
    questions:["Erişim matrisi (rol × kaynak) nerede tutuluyor?","Least privilege nasıl doğrulanıyor?"],
    evidence:["Erişim politikası","Rol-kaynak matrisi","Erişim inceleme raporu"],
    bulgu:"Dev ortamında herkese admin yetkisi verilmiş, justification yok.",
    oneri:"Role-based + JIT elevation; dev için de segregated access ve PAM kurgusu."},
  {code:"A.5.16", name:"Kimlik yönetimi", themeLabel:"A.5 ORG",
    purpose:"Her kullanıcı için tekil, izlenebilir kimlik.",
    questions:["Paylaşımlı hesaplar var mı?","Service account inventory güncel mi?"],
    evidence:["IAM listesi","Service account kayıtları","Orphan hesap raporu"],
    bulgu:"Ortak 'admin' hesabı 4 kişide kullanılıyor, kim ne yaptı takip edilemiyor.",
    oneri:"Tekil hesap + PAM session recording; ortak hesapları tamamen kaldırın."},
  {code:"A.5.17", name:"Kimlik doğrulama bilgileri", themeLabel:"A.5 ORG",
    purpose:"Parola, anahtar, token gibi doğrulama bilgilerinin güvenli yönetimi.",
    questions:["MFA hangi sistemlerde zorunlu?","Parola politikası NIST ile uyumlu mu?"],
    evidence:["Parola politikası","MFA kapsamı raporu","Secret yönetim sistemi"],
    bulgu:"Internet-facing admin paneli MFA'sız, parola 8 karakter minimum.",
    oneri:"Tüm admin & remote erişimde phishing-resistant MFA (FIDO2); şifreler ≥ 14 karakter veya passkey."},
  {code:"A.5.18", name:"Erişim hakları", themeLabel:"A.5 ORG",
    purpose:"Verilmiş erişimlerin düzenli gözden geçirilmesi ve iptali.",
    questions:["Access review periyodu nedir?","Son review'de kaç erişim iptal edildi?"],
    evidence:["Access review raporu","İmzalı onaylar","Değişiklik ticket'ları"],
    bulgu:"Kullanıcı erişim gözden geçirmesi 9 aydır yapılmamış.",
    oneri:"IGA (Identity Governance) + zorunlu çeyreklik review; süreç kaçarsa kritik erişimler otomatik revoke."},
  {code:"A.5.19", name:"Tedarikçi ilişkilerinde bilgi güvenliği", themeLabel:"A.5 ORG",
    purpose:"Tedarikçiler kaynaklı risklerin yönetimi.",
    questions:["Tedarikçi sınıflandırması var mı?","Kritik tedarikçilere hangi güvenlik yükümlülükleri eklendi?"],
    evidence:["Tedarikçi envanteri","Sınıflandırma kriteri","Sözleşme ekleri"],
    bulgu:"Kritik SaaS tedarikçisiyle sözleşmede güvenlik eki yok.",
    oneri:"Standart güvenlik eki (DPA, SLA, audit right, breach notification); kritik olanlara yıllık DD."},
  {code:"A.5.20", name:"Tedarikçi anlaşmalarında güvenlik ele alınması", themeLabel:"A.5 ORG",
    purpose:"Güvenlik gereksinimlerinin sözleşmelerde açıkça yer alması.",
    questions:["Sözleşmelerde incident notification süresi kaç saat?","Audit right klozu var mı?"],
    evidence:["Sözleşme şablonu","Örnek imzalı sözleşme","Legal review kaydı"],
    bulgu:"Sözleşmelerde 'makul süre' ifadesi var, somut saat tanımlı değil.",
    oneri:"72 saat bildirim + 30 gün remediation SLA + pentest paylaşımı gibi somut klozlar tanımlayın."},
  {code:"A.5.21", name:"ICT tedarik zincirinde güvenlik", themeLabel:"A.5 ORG",
    purpose:"Donanım/yazılım tedarik zincirindeki risklerin ele alınması.",
    questions:["SBOM (Software Bill of Materials) hangi ürünler için mevcut?","Üçüncü-parti kütüphane güncelleme politikası nedir?"],
    evidence:["SBOM çıktısı","Vulnerability scan","Vendor risk raporu"],
    bulgu:"Kritik uygulamanın SBOM'u yok; log4shell benzeri olayda etki analizi yapılamadı.",
    oneri:"CI pipeline'da SBOM otomatik üretimi + SCA tarama + known-vuln block policy."},
  {code:"A.5.22", name:"Tedarikçi hizmetlerinin izlenmesi ve gözden geçirilmesi", themeLabel:"A.5 ORG",
    purpose:"Tedarikçi performans ve güvenliğinin düzenli izlenmesi.",
    questions:["Tedarikçi SLA raporları nasıl inceleniyor?","Son 1 yılda kaç tedarikçi review yapıldı?"],
    evidence:["SLA raporları","Yıllık review tutanakları","Sertifika doğrulamaları"],
    bulgu:"Kritik 8 tedarikçiden 3'ünün yıllık review'ü atlanmış.",
    oneri:"Tedarikçi scorecard + otomatik hatırlatıcı; review atlanırsa kontrat yenileme bloklansın."},
  {code:"A.5.23", name:"Bulut hizmetlerinde güvenlik", themeLabel:"A.5 ORG",
    purpose:"Bulut hizmetlerinin güvenli seçim, kullanım ve çıkış stratejisi.",
    questions:["Cloud paylaşılan sorumluluk modeli kurum içinde nasıl belgelenmiş?","Exit planı var mı?"],
    evidence:["Cloud güvenlik baseline","Shared responsibility matris","Exit/portability planı"],
    bulgu:"Kritik SaaS için exit planı yok, vendor lock-in riski kabul edilmiş ama YGG'ye sunulmamış.",
    oneri:"Yıllık data portability test + alternatif vendor matrix; exit playbook'u YGG gündemine alın."},
  {code:"A.5.24", name:"Bilgi güvenliği olay yönetimi planlaması", themeLabel:"A.5 ORG",
    purpose:"Olay yönetimi için plan, rol ve iletişim hazırlığı.",
    questions:["IR playbook'ları son ne zaman test edildi?","Hangi olay sınıfları için playbook var?"],
    evidence:["IR planı","Playbook listesi","Tatbikat kayıtları"],
    bulgu:"Ransomware playbook'u var ama son 18 ayda tatbikatı yapılmamış.",
    oneri:"Yılda 2 kez masa-başı + 1 kez teknik red-team tatbikatı; her playbook'a 'son test' tarihi."},
  {code:"A.5.25", name:"Olayların değerlendirilmesi ve kararı", themeLabel:"A.5 ORG",
    purpose:"Olayların sınıflandırılması ve eskalasyon kriteri.",
    questions:["Severity kriterleri nedir?","Kimin eskalasyon yetkisi var?"],
    evidence:["Severity matrisi","Eskalasyon zinciri","Örnek olay kaydı"],
    bulgu:"Severity tanımı yalnızca sistem downtime'a bağlı, data breach senaryosu kapsam dışı.",
    oneri:"Data breach + tedarikçi + reputational impact eksenlerini severity'ye ekleyin."},
  {code:"A.5.26", name:"Bilgi güvenliği olaylarına yanıt", themeLabel:"A.5 ORG",
    purpose:"Olaylara zamanında ve etkin yanıt.",
    questions:["MTTR son 6 ayda nasıl?","Critical olaylarda kim IC (Incident Commander)?"],
    evidence:["Incident ticket özetleri","Post-mortem raporları","Metriğe dair dashboard"],
    bulgu:"Post-mortem'ler çoğu olayda yazılmıyor, öğrenme döngüsü yok.",
    oneri:"Her Sev1/Sev2 için zorunlu blameless post-mortem; action item'ları JIRA'da takip edin."},
  {code:"A.5.27", name:"Olaylardan öğrenme", themeLabel:"A.5 ORG",
    purpose:"Olay sonrası derslerin sisteme yansıtılması.",
    questions:["Son 1 yılda lessons learned'lerden kaç tanesi gerçekten kapandı?","Tekrar eden olay tipleri neler?"],
    evidence:["Lessons learned arşivi","Aksiyon takip tablosu","Trend analizi"],
    bulgu:"Action item'ların %40'ı 'açık' statüsünde beklerken yeni olaylar aynı kök nedenle tekrarlanıyor.",
    oneri:"Action item kapanmadan yeni benzer olayı 'repeat' olarak etiketleyip CISO'ya eskale edin."},
  {code:"A.5.28", name:"Delil toplama", themeLabel:"A.5 ORG",
    purpose:"Olay delillerinin forensik olarak korunması.",
    questions:["Chain of custody süreci belgeli mi?","Forensic imaj alma kapasiteniz var mı?"],
    evidence:["Forensik prosedür","Custody formu","Araç envanteri"],
    bulgu:"Son incident'ta sunucu restore edildi, forensik imaj alınmadı.",
    oneri:"IR playbook'una 'önce imaj, sonra müdahale' adımını ekleyin; retainer bir forensic firma tutun."},
  {code:"A.5.29", name:"Aksaklık sırasında bilgi güvenliği", themeLabel:"A.5 ORG",
    purpose:"Kesinti/afet anında güvenlik kontrollerinin sürmesi.",
    questions:["DR site için güvenlik baseline aynı mı?","Fallback moddayken hangi kontroller devre dışı kalıyor?"],
    evidence:["DR planı","Güvenlik baseline karşılaştırması","Tatbikat raporu"],
    bulgu:"Fallback sırasında MFA bypass edilebildiği tespit edilmiş ama tedbir alınmamış.",
    oneri:"DR baseline'ını prod ile eşdeğer tutun; 'break-glass' prosedürüne gözden geçirme ve log zorunluluğu koyun."},
  {code:"A.5.30", name:"İş sürekliliği için ICT hazırlığı", themeLabel:"A.5 ORG",
    purpose:"ICT bileşenlerinin iş sürekliliği gereksinimlerini karşılaması.",
    questions:["RPO/RTO'lar iş etki analizine (BIA) göre mi belirlendi?","Son DR testi ne zamandı?"],
    evidence:["BIA raporu","RPO/RTO matrisi","DR test raporu"],
    bulgu:"RPO 1 saat olarak yazılmış ancak yedekleme 24 saatte bir alınıyor.",
    oneri:"Tutarsızlığı kapatın: ya yedekleme sıklığını artırın ya RPO'yu BIA üzerinden revize edin."},
  {code:"A.5.31", name:"Yasal, yönetsel ve sözleşme gereksinimleri", themeLabel:"A.5 ORG",
    purpose:"Uygulanabilir yasal ve sözleşmesel yükümlülüklerin takibi.",
    questions:["KVKK + GDPR + sektörel düzenleyici listesi nerede tutuluyor?","Değişiklikler nasıl izleniyor?"],
    evidence:["Compliance register","Hukuk review kayıtları","Değişiklik bülteni"],
    bulgu:"KVKK veri envanteri 2 yıldır güncellenmemiş.",
    oneri:"Veri envanterine sahip atayın; her yeni sistem onboarding'inde güncelleme zorunlu olsun."},
  {code:"A.5.32", name:"Fikri mülkiyet hakları", themeLabel:"A.5 ORG",
    purpose:"Lisans ve IP gereksinimlerine uyum.",
    questions:["Açık kaynak lisans taraması yapılıyor mu?","Ticari yazılım lisans envanteri güncel mi?"],
    evidence:["SCA tarama","Lisans envanteri","İhlal takip raporu"],
    bulgu:"GPL lisanslı bir kütüphane ticari üründe kullanılıyor, hukuki risk değerlendirilmemiş.",
    oneri:"CI'da license scanner; allow-list dışında kütüphane build'i engellensin."},
  {code:"A.5.33", name:"Kayıtların korunması", themeLabel:"A.5 ORG",
    purpose:"Kayıtların saklama, gizlilik ve bütünlük gereksinimlerinin korunması.",
    questions:["Saklama süre matrisi hangi veri sınıfları için?","Silme/imha süreci nasıl doğrulanıyor?"],
    evidence:["Retention matrisi","İmha tutanakları","Legal hold süreci"],
    bulgu:"Saklama süresi dolmuş kişisel veriler sistemden hâlâ temizlenmemiş.",
    oneri:"Otomatik retention job + silme doğrulama raporu; legal hold flag'i net tanımlayın."},
  {code:"A.5.34", name:"Kişisel verilerin mahremiyeti ve korunması", themeLabel:"A.5 ORG",
    purpose:"Kişisel verilerin yasalara uygun işlenmesi.",
    questions:["Veri işleme envanteri güncel mi?","DPIA hangi işlemler için yapılmış?"],
    evidence:["RoPA / veri envanteri","DPIA raporları","Aydınlatma metinleri"],
    bulgu:"Yeni başlatılan pazarlama kampanyasında DPIA yapılmamış.",
    oneri:"Yeni proje gate'inde DPIA zorunlu checklist; DPO imzası olmadan launch edilemesin."},
  {code:"A.5.35", name:"Bilgi güvenliğinin bağımsız gözden geçirilmesi", themeLabel:"A.5 ORG",
    purpose:"BGYS'nin bağımsız taraflarca periyodik değerlendirilmesi.",
    questions:["İç denetim son ne zaman yapıldı?","Denetçi bağımsızlığı nasıl sağlanıyor?"],
    evidence:["İç denetim raporu","Denetçi CV/bağımsızlık beyanı","Action item takibi"],
    bulgu:"İç denetçi aynı zamanda kontrol sahibi; bağımsızlık ihlali var.",
    oneri:"Denetçi rotasyonu + 3. parti co-sourcing; sahibi olduğu alanı denetlemesin."},
  {code:"A.5.36", name:"Politika, kural ve standartlara uyum", themeLabel:"A.5 ORG",
    purpose:"İç politika ve standartlara uyumun sağlanması.",
    questions:["Uyum izleme hangi KPI'larla yapılıyor?","Sapma durumunda eskalasyon süreci var mı?"],
    evidence:["Uyum dashboard","Sapma raporları","Düzeltici aksiyon kaydı"],
    bulgu:"Uyum sapmaları e-posta ile bildiriliyor, kayıt altına alınmıyor.",
    oneri:"GRC aracında compliance ticket; sapma → risk kaydı → aksiyon zinciri zorunlu olsun."},
  {code:"A.5.37", name:"Dokümante edilmiş işletim prosedürleri", themeLabel:"A.5 ORG",
    purpose:"Operasyonel prosedürlerin yazılı, erişilebilir ve güncel olması.",
    questions:["Runbook kütüphanesi nerede?","Son güncelleme tarihleri nasıl?"],
    evidence:["Runbook envanteri","Versiyon geçmişi","Eğitim kayıtları"],
    bulgu:"Kritik sistemlerin runbook'ları kişisel notlar halinde, kurumsal repo'da yok.",
    oneri:"Merkezi wiki + zorunlu şablon; on-call rotasyonunda her vardiyada runbook quiz."},

  // ============ A.6 KİŞİLER (8) ============
  {code:"A.6.1", name:"Tarama", themeLabel:"A.6 KİŞİ",
    purpose:"İşe alım öncesi referans/özgeçmiş doğrulaması.",
    questions:["Hangi pozisyonlar için background check zorunlu?","Süreç GDPR/KVKK uyumlu mu?"],
    evidence:["Tarama prosedürü","İmzalı onamlar","Sonuç raporları"],
    bulgu:"Kritik pozisyonlarda (sysadmin, DBA) tarama yapılmamış.",
    oneri:"Risk bazlı tarama matrisi; kritik roller için referans + sabıka + finansal kontrol."},
  {code:"A.6.2", name:"İstihdam şartları", themeLabel:"A.6 KİŞİ",
    purpose:"İş sözleşmelerinde güvenlik yükümlülüklerinin yer alması.",
    questions:["İş sözleşmesinde NDA ve güvenlik klozu var mı?","İhlal halinde disiplin süreci belirli mi?"],
    evidence:["Sözleşme şablonu","NDA örneği","İK süreç dokümanı"],
    bulgu:"Sözleşmelerde NDA klozu mevcut ama süresiz yükümlülük belirtilmemiş.",
    oneri:"Post-employment NDA (işten ayrılma sonrası 2–5 yıl) + IP assignment klozu ekleyin."},
  {code:"A.6.3", name:"Bilgi güvenliği farkındalığı, eğitim ve öğretim", themeLabel:"A.6 KİŞİ",
    purpose:"Çalışanların güvenlik farkındalığının geliştirilmesi.",
    questions:["Eğitim tamamlama oranı nedir?","Eğitim etkinliği nasıl ölçülüyor?"],
    evidence:["Eğitim kayıtları","Phishing simülasyon raporu","Quiz sonuçları"],
    bulgu:"Yıllık eğitim tamamlama %97 fakat etkinlik ölçülmüyor; phishing simülasyonu yok.",
    oneri:"Yılda 2 phishing simülasyonu + rol bazlı modüller + tıklama/rapor KPI'ı YGG'ye."},
  {code:"A.6.4", name:"Disiplin süreci", themeLabel:"A.6 KİŞİ",
    purpose:"Güvenlik ihlallerine karşı tanımlı disiplin mekanizması.",
    questions:["Disiplin süreci hukukça onaylı mı?","Son 1 yılda kaç ihlal disipline taşındı?"],
    evidence:["İK politikası","İhlal kayıtları","Karar tutanakları"],
    bulgu:"Disiplin süreci sadece fiziksel güvenlik ihlallerini kapsıyor, veri ihlali tanımsız.",
    oneri:"Bilgi güvenliği ihlal kategorileri ve eşleşen yaptırımları İK yönetmeliğine ekleyin."},
  {code:"A.6.5", name:"İş ilişkisi sonlandıktan veya değiştikten sonraki sorumluluklar", themeLabel:"A.6 KİŞİ",
    purpose:"Ayrılan/rol değişen çalışanların güvenlik yükümlülüklerinin korunması.",
    questions:["Exit görüşmesinde gizlilik hatırlatılıyor mu?","Erişim iptal SLA'sı kaç saat?"],
    evidence:["Exit checklist","İmzalı çıkış formu","Erişim iptal log'u"],
    bulgu:"Exit sonrası erişim iptali ortalama 5 gün sürüyor.",
    oneri:"IK sisteminden IAM'e otomatik webhook; son mesai saati +0 dk disable."},
  {code:"A.6.6", name:"Gizlilik veya ifşa etmeme anlaşmaları", themeLabel:"A.6 KİŞİ",
    purpose:"NDA'ların güncel, taraflı ve saklı olması.",
    questions:["NDA'lar merkezi olarak nerede tutuluyor?","3. taraflar için standart şablon var mı?"],
    evidence:["NDA repo'su","İmza kayıtları","Şablon versiyonları"],
    bulgu:"Harici danışmanlardan 4'ünün NDA'sı bulunamıyor.",
    oneri:"Contract lifecycle management aracı; NDA olmadan kritik erişim verilemesin."},
  {code:"A.6.7", name:"Uzaktan çalışma", themeLabel:"A.6 KİŞİ",
    purpose:"Uzaktan çalışmada bilgi güvenliği kontrollerinin sürmesi.",
    questions:["Home office için asgari teknik gereksinim nedir?","Kişisel cihaz (BYOD) kullanımı nasıl yönetiliyor?"],
    evidence:["Remote work policy","MDM/EDR raporları","Ev ağ güvenliği rehberi"],
    bulgu:"BYOD cihazlarda EDR yok, kritik SaaS'e erişiyorlar.",
    oneri:"MDM + conditional access; uyumlu olmayan cihaz kritik SaaS'e erişemesin."},
  {code:"A.6.8", name:"Bilgi güvenliği olayları raporlama", themeLabel:"A.6 KİŞİ",
    purpose:"Çalışanların olay/şüpheyi kolayca bildirebilmesi.",
    questions:["Tek tıkla ihbar kanalı var mı?","Son 6 ayda çalışan kaynaklı bildirim sayısı?"],
    evidence:["Report Phish butonu","Bildirim süreci","Metrik raporu"],
    bulgu:"Bildirim e-posta adresi var ama çalışanların %60'ı bilmiyor.",
    oneri:"Outlook add-in + yılda 2 farkındalık kampanyası; bildirim yapanlara teşekkür mesajı otomatik."},

  // ============ A.7 FİZİKSEL (14) ============
  {code:"A.7.1", name:"Fiziksel güvenlik çevresi", themeLabel:"A.7 FİZ",
    purpose:"Kurum alanları etrafında tanımlı güvenlik sınırları.",
    questions:["Çevre güvenliği katmanları neler?","CCTV kayıt süresi ne kadar?"],
    evidence:["Saha planı","CCTV spec","Güvenlik vardiya kaydı"],
    bulgu:"DC giriş kapısı mesai dışında kart ile açılıyor, ikinci faktör yok.",
    oneri:"Anti-tailgating turnike + biyometri; DC girişine 2FA zorunlu."},
  {code:"A.7.2", name:"Fiziksel giriş", themeLabel:"A.7 FİZ",
    purpose:"Yetkisiz fiziksel erişimin engellenmesi.",
    questions:["Ziyaretçi kaydı nasıl tutuluyor?","Eskort politikası var mı?"],
    evidence:["Ziyaretçi log'u","Kart erişim raporu","Eskort prosedürü"],
    bulgu:"Ziyaretçi kaydı kağıt defter, son 6 ayın bir kısmı okunmuyor.",
    oneri:"Elektronik ziyaretçi sistemi + foto kaydı + host onayı; aylık erişim review'ü."},
  {code:"A.7.3", name:"Ofis, oda ve tesislerin korunması", themeLabel:"A.7 FİZ",
    purpose:"Hassas alanların ek güvenlikle korunması.",
    questions:["Server room için erişim listesi kaç kişi?","Tanımlanmış no-photo alanlar var mı?"],
    evidence:["Erişim listesi","İşaretleme","Politika"],
    bulgu:"Server room'a 32 kişi erişebiliyor; bunun 12'sinin iş gereği yok.",
    oneri:"Erişim listesini review edin; 'ihtiyaç' yoksa revoke. Listeyi çeyreklik imzalı tutun."},
  {code:"A.7.4", name:"Fiziksel güvenlik izleme", themeLabel:"A.7 FİZ",
    purpose:"Fiziksel alanların sürekli gözetimi.",
    questions:["CCTV kayıt periyodu ve saklama?","Alarm sistemi SOC'a bağlı mı?"],
    evidence:["CCTV config","Alarm test kayıtları","Olay örnekleri"],
    bulgu:"CCTV bir lokasyonda kayıt yapıyor ancak alarm SOC'a ulaşmıyor.",
    oneri:"Alarm → SOC entegrasyonu + quarterly test drill; test kaydını tutun."},
  {code:"A.7.5", name:"Fiziksel ve çevresel tehditlere karşı koruma", themeLabel:"A.7 FİZ",
    purpose:"Yangın, su, deprem gibi çevresel tehditlere karşı koruma.",
    questions:["DC yangın söndürme sistemi nedir?","Su baskını sensörü var mı?"],
    evidence:["Tesis raporu","Test kayıtları","Sigorta poliçesi"],
    bulgu:"DC'de FM200 var ama son test 3 yıl önce yapılmış.",
    oneri:"Yıllık test + sertifika yenileme; test atlanırsa risk kaydı açılsın."},
  {code:"A.7.6", name:"Güvenli alanlarda çalışma", themeLabel:"A.7 FİZ",
    purpose:"Güvenli alanlarda çalışma kurallarının tanımlanması.",
    questions:["DC'de cep telefonu/kamera yasak mı?","Temizlik personeli eskortlu mu?"],
    evidence:["DC davranış kuralları","Eskort kayıtları","İhlal kaydı"],
    bulgu:"Temizlik personeli DC'ye eskortsuz giriyor.",
    oneri:"Eskort zorunlu; temizlik saatlerinde mutlaka BT refakat + kayıt."},
  {code:"A.7.7", name:"Temiz masa ve temiz ekran", themeLabel:"A.7 FİZ",
    purpose:"Masa ve ekranların açık bilgi içermemesi.",
    questions:["Otomatik ekran kilidi ne kadar?","Kağıt imha kutuları mevcut mu?"],
    evidence:["Politika","Walk-through raporu","Shredder kayıtları"],
    bulgu:"Çeyreklik walk-through yapılmış, 14 ihlal gözlenmiş ama aksiyon yok.",
    oneri:"İhlal → çalışan farkındalık ticket + ikinci ihlalde yönetici uyarısı."},
  {code:"A.7.8", name:"Ekipmanların yerleştirilmesi ve korunması", themeLabel:"A.7 FİZ",
    purpose:"Kritik ekipmanın fiziksel tehditlerden uzak konumlandırılması.",
    questions:["Ekipmanlar yüksekte mi (su baskınına karşı)?","Pencere yakınında kritik sunucu var mı?"],
    evidence:["Saha yerleşimi","Risk değerlendirme"],
    bulgu:"Yedek sunucu bodrum katta, geçmişte 1 kez su baskını yaşanmış.",
    oneri:"Ekipmanı yukarı taşıyın ya da flood-resistant kabin kullanın; sensör + alarm ekleyin."},
  {code:"A.7.9", name:"Tesis dışındaki varlıkların güvenliği", themeLabel:"A.7 FİZ",
    purpose:"Sahada/ev ortamında bulunan ekipmanın korunması.",
    questions:["Saha çalışanı cihazları nasıl izleniyor?","Kaybolan cihaz prosedürü var mı?"],
    evidence:["MDM raporu","Kayıp ihbar kaydı","Şifreleme doğrulama"],
    bulgu:"Dizüstü cihazlarda disk şifrelemesi %82 aktif, kalanı belirsiz.",
    oneri:"Compliance %100 hedef; uyumsuz cihaz MDM ile karantinaya alınsın."},
  {code:"A.7.10", name:"Depolama ortamı", themeLabel:"A.7 FİZ",
    purpose:"Taşınabilir ortam/medya güvenliği.",
    questions:["USB kullanımı nasıl denetleniyor?","Medya etiketleme politikası?"],
    evidence:["DLP/USB policy","Medya envanteri","İmha kayıtları"],
    bulgu:"USB sınırsız kullanılıyor, DLP yok.",
    oneri:"USB encrypt veya block; onaylı listede olmayan cihaz mount edilemesin."},
  {code:"A.7.11", name:"Destek altyapıları", themeLabel:"A.7 FİZ",
    purpose:"Elektrik, iklimlendirme, network gibi destek hizmetlerinin güvenilirliği.",
    questions:["UPS kapasitesi ne kadar?","Jeneratör test sıklığı?"],
    evidence:["UPS spec","Jeneratör test log'u","İklimlendirme raporu"],
    bulgu:"Jeneratör testi yılda 1, son test 14 ay önce.",
    oneri:"Aylık no-load + yıllık full-load test; test kaçırma escalation."},
  {code:"A.7.12", name:"Kablolama güvenliği", themeLabel:"A.7 FİZ",
    purpose:"Güç ve veri kablolarının fiziksel korunması.",
    questions:["Patch panel erişimi kısıtlı mı?","Kablolar etiketli mi?"],
    evidence:["Kablo yönetim politikası","Saha fotoğrafı","Label envanteri"],
    bulgu:"Ana switch odası kilitli değil, patch panel açıkta.",
    oneri:"Rack kilitli + erişim log; etiketleme + yıllık foto envanter."},
  {code:"A.7.13", name:"Ekipmanların bakımı", themeLabel:"A.7 FİZ",
    purpose:"Ekipman bakımının güvenli yapılması.",
    questions:["Bakım için 3. taraf eskortlu mu?","Periyodik bakım takvimi var mı?"],
    evidence:["Bakım takvimi","Servis kayıtları","Eskort kayıtları"],
    bulgu:"3. taraf teknisyen DC'de eskortsuz çalışmış.",
    oneri:"Her dış bakım için BT eskortu + session recording; önceden onay süreci."},
  {code:"A.7.14", name:"Ekipmanın güvenli elden çıkarılması veya yeniden kullanımı", themeLabel:"A.7 FİZ",
    purpose:"Kullanım dışı ekipmandaki verilerin güvenli imhası.",
    questions:["Disk imha yöntemi nedir?","Sertifika sunuluyor mu?"],
    evidence:["İmha sertifikaları","Envanter closeout","Tedarikçi sözleşmesi"],
    bulgu:"Eski laptoplar formatlanarak satışa çıkarılmış, secure wipe yok.",
    oneri:"NIST 800-88 sanitization + 3. parti imha sertifikası; envanterde 'disposed' statü + hash."},

  // ============ A.8 TEKNOLOJİK (34) ============
  {code:"A.8.1", name:"Kullanıcı uç nokta cihazları", themeLabel:"A.8 TEK",
    purpose:"Uç nokta cihazlarının güvenli yapılandırılması.",
    questions:["EDR hangi cihazlarda kurulu?","Disk şifrelemesi oranı?"],
    evidence:["EDR dashboard","BitLocker/FileVault raporu","Politika"],
    bulgu:"EDR kapsam %88; Mac'lerin yarısında agent yok.",
    oneri:"MDM ile EDR zorunlu; uyumsuz cihaz corporate SSO'ya login olamasın."},
  {code:"A.8.2", name:"Ayrıcalıklı erişim hakları", themeLabel:"A.8 TEK",
    purpose:"Admin/priv. hesapların sıkı yönetilmesi.",
    questions:["PAM aracı kullanılıyor mu?","Just-in-time elevation var mı?"],
    evidence:["PAM envanteri","JIT politika","Session recording örneği"],
    bulgu:"Sysadmin'ler 7/24 açık admin hesaplarıyla çalışıyor.",
    oneri:"JIT elevation + PAM vault + session recording; kalıcı admin hakları kaldırılsın."},
  {code:"A.8.3", name:"Bilgi erişim kısıtlaması", themeLabel:"A.8 TEK",
    purpose:"Bilgi sistemlerine erişimin iş gereksinimine göre kısıtlanması.",
    questions:["Uygulama içi yetki matrisi var mı?","ABAC/RBAC kullanımı?"],
    evidence:["Uygulama yetki config","Rol envanteri","Audit raporu"],
    bulgu:"HR uygulamasında herkes tüm çalışan maaşlarını görebiliyor.",
    oneri:"Row-level security; yalnızca line manager + HRBP görsün."},
  {code:"A.8.4", name:"Kaynak koda erişim", themeLabel:"A.8 TEK",
    purpose:"Kaynak kodunun gizlilik ve bütünlüğünün korunması.",
    questions:["Repo erişimi SSO ile mi?","Secret scanning aktif mi?"],
    evidence:["Git ACL","Secret scan raporu","Branch protection rules"],
    bulgu:"Repo'larda commit edilmiş 14 adet API key tespit edildi.",
    oneri:"Secret scanning block on push + rotate; pre-commit hook ile lokal kontrol."},
  {code:"A.8.5", name:"Güvenli kimlik doğrulama", themeLabel:"A.8 TEK",
    purpose:"Güvenli kimlik doğrulama teknikleri kullanılması.",
    questions:["Phishing-resistant MFA hangi sistemlerde?","Legacy auth bloklandı mı?"],
    evidence:["MFA kapsam matrisi","Legacy auth raporu","SSO envanteri"],
    bulgu:"SMS OTP hâlâ ana MFA yöntemi.",
    oneri:"FIDO2/Passkey'e geçiş roadmap'i; SMS fallback'i yüksek riskli kullanıcılar için kapatın."},
  {code:"A.8.6", name:"Kapasite yönetimi", themeLabel:"A.8 TEK",
    purpose:"Kaynak kapasitesinin gelecek ihtiyaçlara göre izlenmesi.",
    questions:["Kapasite eşik alarmları var mı?","Forecast ne kadar ileriye?"],
    evidence:["Monitoring dashboard","Alert config","Forecast raporu"],
    bulgu:"Storage kapasite alarmı eşiği %95; hedef 85'e inmeliydi.",
    oneri:"Eşikleri review edin; tier'lı uyarı (warn %75 / crit %85); 6-aylık forecast zorunlu."},
  {code:"A.8.7", name:"Kötü amaçlı yazılıma karşı koruma", themeLabel:"A.8 TEK",
    purpose:"Malware'e karşı koruma.",
    questions:["NGAV/EDR vendor nedir?","Behavior-based detection oranı?"],
    evidence:["EDR config","Detection istatistiği","Örnek olay"],
    bulgu:"Malware detection yalnızca signature; behavior-based modül lisansı alınmamış.",
    oneri:"Behavioral + ML tabanlı detection aktive edin; EDR telemetry'yi SIEM'e forward."},
  {code:"A.8.8", name:"Teknik açıklıkların yönetimi", themeLabel:"A.8 TEK",
    purpose:"Vulnerability management döngüsü.",
    questions:["Patch SLA critical için?","VM tool hangisi?"],
    evidence:["VM raporu","Patch dashboard","Exception log"],
    bulgu:"Critical CVE için patch SLA 30 gün, gerçekleşme ortalama 52 gün.",
    oneri:"Critical için 14 gün; 7 gün içinde virtual patching; SLA ihlali → risk kaydı."},
  {code:"A.8.9", name:"Konfigürasyon yönetimi", themeLabel:"A.8 TEK",
    purpose:"Sistemlerin güvenli baseline'a göre yapılandırılması.",
    questions:["CIS benchmark skorları nasıl?","Drift detection var mı?"],
    evidence:["Benchmark raporu","CMDB","Drift alarmları"],
    bulgu:"Server baseline %60 uyumlu; drift takibi manuel.",
    oneri:"IaC + policy-as-code; drift anında SIEM alarmı + otomatik remediation."},
  {code:"A.8.10", name:"Bilgilerin silinmesi", themeLabel:"A.8 TEK",
    purpose:"İhtiyaç kalmayan bilginin güvenli silinmesi.",
    questions:["GDPR silme talebi nasıl işliyor?","Yedeklerden silme mümkün mü?"],
    evidence:["DSAR/erasure log","Yedek retention","Silme doğrulama"],
    bulgu:"Silme talebi sonrası yedeklerde veri kalıyor, prosedürde yazılı değil.",
    oneri:"Yedek retention + legal hold süreci; silmenin yedeklerle nasıl örtüşeceği netleşsin."},
  {code:"A.8.11", name:"Veri maskeleme", themeLabel:"A.8 TEK",
    purpose:"Hassas verinin test/dev ortamında maskelenmesi.",
    questions:["Non-prod'da gerçek üretim verisi var mı?","Maskeleme aracı?"],
    evidence:["Masking config","Sample non-prod data","Erişim log"],
    bulgu:"Test ortamında üretim PII'si maskelenmeden kullanılıyor.",
    oneri:"Synthetic data + deterministic masking; gerçek veri non-prod'a asla kopyalanmasın."},
  {code:"A.8.12", name:"Veri sızıntısı önleme", themeLabel:"A.8 TEK",
    purpose:"Hassas verinin izinsiz çıkışının engellenmesi.",
    questions:["DLP hangi kanallarda (mail, endpoint, cloud)?","Son 6 ayda kaç bulgu?"],
    evidence:["DLP policy matrisi","Bulgu raporu","İstisna kayıtları"],
    bulgu:"DLP yalnızca e-postada; USB ve cloud sync kapsam dışı.",
    oneri:"Endpoint DLP + CASB aktive edin; üç kanalda tek policy framework."},
  {code:"A.8.13", name:"Bilgi yedekleme", themeLabel:"A.8 TEK",
    purpose:"Yedekleme ve geri yükleme süreçlerinin etkin olması.",
    questions:["Son başarılı restore testi ne zaman?","3-2-1 kuralına uyum var mı?"],
    evidence:["Yedek takvimi","Restore test raporu","Immutable backup kaydı"],
    bulgu:"Restore testi yılda 1, son testte %30 başarısızlık.",
    oneri:"Çeyreklik tabletop restore + immutable (WORM) yedek; başarısızlık → ticket + retest."},
  {code:"A.8.14", name:"Bilgi işleme tesislerinin yedekliliği", themeLabel:"A.8 TEK",
    purpose:"Kritik sistemlerin failover kapasitesi.",
    questions:["Active-active mi active-passive mi?","Son failover testi?"],
    evidence:["Mimari diyagram","DR test raporu","RTO ölçümü"],
    bulgu:"Failover testi prodüksiyon etkisi korkusuyla 2 yıldır yapılmamış.",
    oneri:"Gameday formatında kontrollü test; chaos engineering kültürünü aşamalı benimsetin."},
  {code:"A.8.15", name:"Log'lama", themeLabel:"A.8 TEK",
    purpose:"Olay log'larının üretimi, toplanması ve korunması.",
    questions:["Log retention politikası?","Log integrity (WORM/hash) nasıl?"],
    evidence:["SIEM config","Retention raporu","Integrity kontrol örneği"],
    bulgu:"Kritik 2 DB'de audit log saklama süresi politikadaki 12 ayın altında.",
    oneri:"Merkezi SIEM + 12 ay cold storage; append-only veya imza zinciri."},
  {code:"A.8.16", name:"İzleme faaliyetleri", themeLabel:"A.8 TEK",
    purpose:"Anomaly ve güvenlik olaylarının tespiti için izleme.",
    questions:["SOC kapsamı nedir?","MTTD ortalama?"],
    evidence:["SOC runbook","MTTD/MTTR dashboard","Use-case envanteri"],
    bulgu:"Use-case kütüphanesi yok; detection ad-hoc.",
    oneri:"MITRE ATT&CK mapping + use-case katalog + coverage gap raporu."},
  {code:"A.8.17", name:"Saat senkronizasyonu", themeLabel:"A.8 TEK",
    purpose:"Sistemlerin tutarlı zaman kaynağına senkronize olması.",
    questions:["NTP kaynağı hangisi?","Time drift alarmı var mı?"],
    evidence:["NTP config","Drift dashboard"],
    bulgu:"Bazı sunucular internet NTP'ye doğrudan bağlı; iç NTP yok.",
    oneri:"Stratum-1 iç NTP + drift ≥ 100ms alarm; forensik değerlendirme kritik."},
  {code:"A.8.18", name:"Ayrıcalıklı programların kullanımı", themeLabel:"A.8 TEK",
    purpose:"Güçlü araçların (admin tool) denetimli kullanımı.",
    questions:["Admin araçları allowlist'te mi?","Kullanım log'u tutuluyor mu?"],
    evidence:["AppLocker/WDAC","Kullanım raporu"],
    bulgu:"PowerShell unconstrained modda; script block logging kapalı.",
    oneri:"Constrained language mode + transcript + script block logging → SIEM."},
  {code:"A.8.19", name:"İşletim sistemlerine yazılım kurulumu", themeLabel:"A.8 TEK",
    purpose:"Yazılım kurulumunun yetkili ve denetimli olması.",
    questions:["Kullanıcı local admin hakkına sahip mi?","Uygulama allowlist var mı?"],
    evidence:["MDM config","Allowlist politikası","Kurulum log'u"],
    bulgu:"Dev makinelerinde local admin herkese açık.",
    oneri:"LAPS + privilege elevation aracı; geliştirici için kontrollü yükseltme."},
  {code:"A.8.20", name:"Ağ güvenliği", themeLabel:"A.8 TEK",
    purpose:"Ağların korunması, segmentasyonu ve yönetimi.",
    questions:["Flat network mi, segmentli mi?","East-west trafiğin görünürlüğü?"],
    evidence:["Ağ diyagramı","Segment matrisi","NDR/flow logs"],
    bulgu:"Flat network; IoT cihazları finans VLAN'ıyla aynı.",
    oneri:"Macro + micro segmentasyon; zero-trust prensibi ile east-west kontrol."},
  {code:"A.8.21", name:"Ağ hizmetlerinin güvenliği", themeLabel:"A.8 TEK",
    purpose:"Ağ servis SLA ve güvenlik özelliklerinin tanımlı olması.",
    questions:["ISP ile güvenlik eki imzalı mı?","DDoS mitigation var mı?"],
    evidence:["Sözleşme ekleri","DDoS raporu","SLA ölçümü"],
    bulgu:"ISP sözleşmesinde DDoS SLA tanımsız.",
    oneri:"Scrubbing center + always-on DDoS; SLA'yı 'resolved in X min' olarak somutlayın."},
  {code:"A.8.22", name:"Ağların ayrılması", themeLabel:"A.8 TEK",
    purpose:"Farklı güvenlik bölgelerinin mantıksal ayrılığı.",
    questions:["OT/IT ayrımı nasıl?","Admin VLAN ayrılmış mı?"],
    evidence:["VLAN planı","Firewall kuralı","Bastion konfigürasyonu"],
    bulgu:"Admin VLAN kullanıcı VLAN ile aynı; jump server yok.",
    oneri:"Dedicated admin VLAN + bastion host + MFA + session recording."},
  {code:"A.8.23", name:"Web filtreleme", themeLabel:"A.8 TEK",
    purpose:"Zararlı/uygunsuz web trafiğinin engellenmesi.",
    questions:["SWG/DNS filtering hangi kategorileri bloklar?","Uzak çalışanda koruma var mı?"],
    evidence:["SWG policy","Blok istatistikleri","Off-network raporu"],
    bulgu:"Off-network çalışanlarda DNS filtering yok.",
    oneri:"Cloud SWG / DNS-layer koruma; her cihaz network bağımsız korunur."},
  {code:"A.8.24", name:"Kriptografi kullanımı", themeLabel:"A.8 TEK",
    purpose:"Şifreleme algoritma, anahtar ve yaşam döngüsü yönetimi.",
    questions:["Kripto politikası güncel mi?","HSM/KMS kullanımı?"],
    evidence:["Crypto policy","Anahtar envanteri","Rotation kayıtları"],
    bulgu:"Bazı servislerde TLS 1.0/1.1 hâlâ destekleniyor.",
    oneri:"TLS 1.2+ zorunlu; quarterly tarama; anahtar rotation ≤ 12 ay."},
  {code:"A.8.25", name:"Güvenli geliştirme yaşam döngüsü", themeLabel:"A.8 TEK",
    purpose:"SSDLC süreçlerinin işletilmesi.",
    questions:["Threat modeling hangi projeler için?","Secure coding eğitimi?"],
    evidence:["SSDLC doküman","Threat model örnekleri","Eğitim kayıtları"],
    bulgu:"Threat modeling ad-hoc; SSDLC yazılı değil.",
    oneri:"STRIDE/LINDDUN tabanlı şablon + kritik proje gate; developer eğitimi yıllık."},
  {code:"A.8.26", name:"Uygulama güvenliği gereksinimleri", themeLabel:"A.8 TEK",
    purpose:"Uygulamaların güvenlik gereksinimlerinin baştan tanımlanması.",
    questions:["Her epic'te security acceptance criteria var mı?","ASVS seviyesi belirli mi?"],
    evidence:["Epic şablonu","ASVS matrisi","Review kayıtları"],
    bulgu:"Security gereksinimleri sadece critical projelerde tanımlanıyor.",
    oneri:"Template'e 'security reqs' bölümü zorunlu; ASVS L2 default baseline."},
  {code:"A.8.27", name:"Güvenli sistem mimarisi ve mühendislik prensipleri", themeLabel:"A.8 TEK",
    purpose:"Mimari seviyede güvenlik prensiplerinin uygulanması.",
    questions:["Zero-trust prensipleri nasıl uygulanıyor?","Architecture review süreci?"],
    evidence:["Mimari kararlar (ADR)","Security review tutanakları","Referans mimari"],
    bulgu:"Yeni servis mimarilerinin %30'unda güvenlik review yapılmamış.",
    oneri:"Architecture review board'a security seat zorunlu; ADR'ye security bölümü."},
  {code:"A.8.28", name:"Güvenli kodlama", themeLabel:"A.8 TEK",
    purpose:"Güvenli kodlama standartları ve pratiklerinin uygulanması.",
    questions:["SAST/DAST hangi dil ve pipeline'da?","Coding standard dokümante mi?"],
    evidence:["SAST/DAST config","Standard doküman","Finding triage raporu"],
    bulgu:"SAST var ama bulgular triaj edilmeden kapatılıyor.",
    oneri:"Severity'ye göre SLA + zorunlu triage; high ve üstü prod'a gitmesin."},
  {code:"A.8.29", name:"Geliştirme ve kabul testi", themeLabel:"A.8 TEK",
    purpose:"Uygulamanın güvenlik testlerinden geçmesi.",
    questions:["Pentest sıklığı?","Bug bounty var mı?"],
    evidence:["Pentest raporları","Bounty istatistikleri","Düzeltme kanıtı"],
    bulgu:"Kritik uygulama yıllık pentest'ten geçmemiş.",
    oneri:"Yılda 1 external pentest + sürekli bug bounty; kritik bulgu → acil patch SLA."},
  {code:"A.8.30", name:"Dış kaynaklı geliştirme", themeLabel:"A.8 TEK",
    purpose:"Dış kaynakla geliştirilen yazılımın güvenliği.",
    questions:["Vendor için secure code review zorunlu mu?","Teslimat öncesi pentest?"],
    evidence:["Sözleşme eki","Review raporu","Teslim-kabul formu"],
    bulgu:"Outsource kod 'as-is' teslim alınıyor; review yapılmıyor.",
    oneri:"Teslim öncesi SAST + manual review + bulgu kapanış şartı sözleşmede."},
  {code:"A.8.31", name:"Geliştirme, test ve üretim ortamlarının ayrılması", themeLabel:"A.8 TEK",
    purpose:"Ortamlar arası mantıksal ve fiziksel ayrılık.",
    questions:["Dev'den prod'a erişim mümkün mü?","Veri akışı tek yönlü mü?"],
    evidence:["Ağ diyagramı","IAM matris","Data flow diyagramı"],
    bulgu:"Dev makineden prod DB'ye doğrudan erişim var.",
    oneri:"Ortamlar arasında firewall + bastion; data akışı yalnızca prod → non-prod (maskelenmiş)."},
  {code:"A.8.32", name:"Değişiklik yönetimi", themeLabel:"A.8 TEK",
    purpose:"Değişikliklerin kontrollü yapılması.",
    questions:["Emergency change süreci belgeli mi?","CAB onay oranı?"],
    evidence:["Change record","CAB tutanak","Emergency justification"],
    bulgu:"Acil değişikliklerin %35'i geriye dönük onaylanıyor.",
    oneri:"Emergency template + 48 saat içinde retrospektif onay; %5'e düşürmeyi hedefleyin."},
  {code:"A.8.33", name:"Test bilgileri", themeLabel:"A.8 TEK",
    purpose:"Test verisinin güvenli seçimi, korunması ve kontrolü.",
    questions:["Test verisi kaynağı nedir?","Maskeleme süreci var mı?"],
    evidence:["Test data management tool","Maskeleme raporu","Erişim log'u"],
    bulgu:"Test verisi prod'dan copy yapılıyor; erişim kontrolü prod'dan zayıf.",
    oneri:"Synthetic + deterministic masking; test veri access prod ile aynı seviyede korunsun."},
  {code:"A.8.34", name:"Denetim testleri sırasında bilgi sistemlerinin korunması", themeLabel:"A.8 TEK",
    purpose:"Denetim aktivitelerinin prod etkisinin minimize edilmesi.",
    questions:["Denetim testleri prod'u etkileyebilir mi?","Read-only erişim kuralı var mı?"],
    evidence:["Denetim kapsam dokümanı","Erişim onayı","İzleme log'u"],
    bulgu:"Denetçilere write yetkisi verilmiş, neden yazılı değil.",
    oneri:"Denetçi erişimleri default read-only; write gerekiyorsa justification + 4-gözlü onay."}
];
